#!/usr/bin/env bash
if [ -z "$APP" ]; then
  APP=$(cat package.json | jq '.id' | tr -d '"')
fi
echo APP=$APP
BUILD_DIR="build"
Build() {
  flatpak-builder --force-clean $BUILD_DIR $APP.json
}
Install() {
  flatpak-builder --user --install --force-clean $BUILD_DIR $APP.json
}
Debug() {
  flatpak-builder --run $BUILD_DIR $APP.json sh
}
Help() {
  echo "$(basename $0) [verb]"
  echo "  Verbs:"
  echo "    [build, install, run, help]"
  echo "    at least 1"
}
if [[ $# -lt 1 ]]; then
  Help
  exit 1
fi
for arg in ${@}; do
  case "$arg" in
  build)
    if ! Build; then
      exit $?
    fi
    ;;
  install)
    if ! Install; then
      exit $?
    fi
    ;;
  run)
    flatpak -vvvv run $APP
    exit $?
    ;;
  uninstall)
    flatpak uninstall $APP -y
    ;;
  help)
    Help
    exit
    ;;
  debug)
    Debug
    exit $?
    ;;
  *)
    echo "$(basename $0): Unknown command '$arg'" >&2
    exit 1
    ;;
  esac
done
